async (page) => {
  const failures=[];
  const check=(value,message)=>{if(!value)failures.push(message)};
  await page.bringToFront();
  await page.waitForFunction(()=>window.__NEON_NEXT__);
  const read=()=>page.evaluate(()=>window.__NEON_NEXT__.snapshot());
  if((await read()).mode!=='inspection')await page.getByRole('button',{name:'← The armory'}).click();
  await page.getByRole('button',{name:'Compare two knights'}).click();
  check((await read()).actors===2,'Independent instance comparison missing');
  await page.getByRole('button',{name:'Pause movement',exact:true}).click();
  const frozen=await read();await page.waitForTimeout(250);const independent=await read();
  check(independent.hero.time===frozen.hero.time && independent.partner.time>frozen.partner.time,'Character animation clocks are not independent');
  await page.getByRole('button',{name:'Resume movement',exact:true}).click();
  await page.getByRole('combobox',{name:'ANIMATION'}).selectOption('bow_hold');
  await page.screenshot({path:'output/playwright/foundry-bow-hold.png'});
  await page.getByRole('button',{name:'02 Sunlance'}).click();
  check((await read()).weapon==='sunlance','Inspection weapon switch failed');
  await page.screenshot({path:'output/playwright/foundry-sunlance.png'});
  await page.getByRole('button',{name:'Enter the courtyard ↗'}).click();
  const start=await read();
  await page.keyboard.down('KeyD');await page.waitForTimeout(350);await page.keyboard.up('KeyD');
  await page.waitForTimeout(100);
  check((await read()).player.x>start.player.x+.5,'Continuous horizontal movement failed');
  await page.getByRole('button',{name:'Restore company',exact:true}).first().click();
  const box=await page.locator('.field-stage').boundingBox();
  await page.mouse.move(box.x+box.width*.5,box.y+box.height*.27);
  await page.mouse.down();await page.waitForTimeout(1900);await page.mouse.up();
  const shot=await read();check(shot.shots>=1,'Primary did not release');check(shot.hits>=1,'Projectile did not strike target');
  await page.waitForTimeout(1000);await page.keyboard.press('KeyQ');await page.waitForTimeout(1300);
  check((await read()).player.weapon==='sunlance','Weapon swap failed');
  const beforeDodge=await read();await page.keyboard.press('Space');await page.waitForTimeout(120);
  check((await read()).dodgeCharges===beforeDodge.dodgeCharges-1,'Dodge charge not consumed');
  await page.keyboard.down('Tab');await page.mouse.click(box.x+box.width*.40,box.y+box.height*.52);await page.keyboard.up('Tab');
  await page.waitForTimeout(120);check((await read()).order==='hold','Company order failed');
  await page.getByRole('button',{name:'Start ward trial'}).click();await page.waitForTimeout(3000);
  const trial=await read();check(trial.damage>0,'Ward never resolved against a stationary commander');
  await page.keyboard.press('Escape');const paused=await read();await page.waitForTimeout(300);
  check((await read()).time===paused.time,'Pause did not freeze simulation');
  await page.screenshot({path:'output/playwright/courtyard-pause.png'});
  await page.getByRole('button',{name:'Return to the courtyard'}).click();
  await page.screenshot({path:'output/playwright/courtyard-verified.png'});
  const result={failures,inspectionActors:2,primary:{shots:shot.shots,hits:shot.hits},trial:{damage:trial.damage,company:trial.company.length},final:await read()};
  if(failures.length)throw new Error(JSON.stringify(result));
  return result;
}
